CREATE DATABASE COSMOS;
USE COSMOS;

CREATE TABLE USER_PROFILE (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NICKNAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(100) NOT NULL,
    USER_COUNTRY VARCHAR(100) NOT NULL,
    USER_BIRTH DATE NOT NULL
);

CREATE TABLE GAME_LEVELS (
    LEVEL_ID INT AUTO_INCREMENT PRIMARY KEY,
    LEVEL_NAME VARCHAR(100) NOT NULL,
    LEVEL_DIFFICULTY INT NOT NULL,
);

CREATE TABLE USER_LEVEL_SCORE (
    SCORE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    LEVEL_ID INT NOT NULL,
    POINTS INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID),
    FOREIGN KEY (LEVEL_ID) REFERENCES GAME_LEVELS(LEVEL_ID)
);
